<?php

namespace AppBundle\Repository;

/**
 * StenographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StenographyRepository extends \Doctrine\ORM\EntityRepository
{
}
